/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.pharmacy;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.PharmacyProfile;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JPanel;

/**
 *
 * @author shrey
 */
public class LandingPagePharma extends javax.swing.JPanel {

    /**
     * Creates new form LandingPagePharma
     */
       javax.swing.JPanel CardSequencePanel;
   Business business;
    PharmacyProfile pharmacyProfile;
    Properties properties;
    public LandingPagePharma(JPanel CardSequencePanel,Business business, PharmacyProfile pharmacyProfile, Properties properties) {
       initComponents();
                this.CardSequencePanel=CardSequencePanel;
        this.business=business;
        this.pharmacyProfile = pharmacyProfile;
        this.properties=properties;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageMed = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        btnManageMed.setText("Manage Medicine");
        btnManageMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMedActionPerformed(evt);
            }
        });

        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });

        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnManageOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageMed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btnManageMed)
                .addGap(18, 18, 18)
                .addComponent(btnManageOrders)
                .addGap(18, 18, 18)
                .addComponent(btnDashboard)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMedActionPerformed
        // TODO add your handling code here:
                  ViewMedJPanel viewMedJPanel=new ViewMedJPanel(CardSequencePanel,business,pharmacyProfile,properties);
        CardSequencePanel.add("ViewMedJPanel", viewMedJPanel);
        CardLayout layout=(CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
        
    }//GEN-LAST:event_btnManageMedActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageOrdersActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnManageMed;
    private javax.swing.JButton btnManageOrders;
    // End of variables declaration//GEN-END:variables
}
