/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.pharmacy;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.PharmacyProfile;
import com.enterprise.main.directory.Medicine;
import com.enterprise.main.directory.MedicineCatalog;
import com.enterprise.main.directory.PharmacyDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrey
 */
public class UpdateMedJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMedJPanel
     */
    
           javax.swing.JPanel CardSequencePanel;
    Business business;
    PharmacyProfile pharmacyProfile;
    Properties properties;
    Medicine selectedMedicine;
    
    public UpdateMedJPanel(JPanel CardSequencePanel, Business business, PharmacyProfile pharmacyProfile, Properties properties, Medicine selectedMedicine) {
        initComponents();
          this.CardSequencePanel=CardSequencePanel;
        this.business=business;
        this.pharmacyProfile = pharmacyProfile;
        this.properties=properties;
         this.selectedMedicine = selectedMedicine;

        if (selectedMedicine != null) {
            txtMedName.setText(selectedMedicine.getMedName());
            txtExpDate.setText(selectedMedicine.getExpiryDate());
                        txtPrice.setText(String.valueOf(selectedMedicine.getPrice()));

            if (selectedMedicine.isMedAvail()) {
                radioAvail.setSelected(true);
            } else {
                radioUnavail.setSelected(true);
            }
        
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioUnavail = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblStockAvail1 = new javax.swing.JLabel();
        txtExpDate1 = new java.awt.TextField();
        lblMedName = new javax.swing.JLabel();
        lblExpDate = new javax.swing.JLabel();
        lblStockAvail = new javax.swing.JLabel();
        txtMedName = new java.awt.TextField();
        txtExpDate = new java.awt.TextField();
        radioAvail = new javax.swing.JRadioButton();
        lblStockAvail2 = new javax.swing.JLabel();
        txtPrice = new java.awt.TextField();

        radioUnavail.setText("Unavailaible");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblStockAvail1.setText("Medicine ID");

        txtExpDate1.setEditable(false);
        txtExpDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpDate1ActionPerformed(evt);
            }
        });

        lblMedName.setText("Medicine Name");

        lblExpDate.setText("Expiry Date");

        lblStockAvail.setText("Stock Availaibility");

        txtExpDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExpDateActionPerformed(evt);
            }
        });

        radioAvail.setText("Availaible");
        radioAvail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAvailActionPerformed(evt);
            }
        });

        lblStockAvail2.setText("Price");

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(btnUpdate)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblStockAvail2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedName)
                            .addComponent(lblExpDate)
                            .addComponent(lblStockAvail)
                            .addComponent(lblStockAvail1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(radioAvail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioUnavail)
                                .addGap(55, 55, 55))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtExpDate1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMedName)
                            .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblExpDate))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStockAvail)
                            .addComponent(radioAvail)
                            .addComponent(radioUnavail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStockAvail1)
                            .addComponent(txtExpDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblStockAvail2))
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnUpdate)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout = (CardLayout) CardSequencePanel.getLayout();
        layout.previous(CardSequencePanel);

        Component previousComponent = CardSequencePanel.getComponent(CardSequencePanel.getComponentCount() - 1);
        if (previousComponent instanceof ViewMedJPanel) {
            ViewMedJPanel viewMedJPanel = (ViewMedJPanel) previousComponent;
            viewMedJPanel.refreshMedicineTable();
        } else {
            System.out.println("Error: Previous component is not an instance of ViewMedJPanel");
        }

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
      if (selectedMedicine != null) {
        // Update fields except for Medicine ID
        selectedMedicine.setMedName(txtMedName.getText());
        selectedMedicine.setExpiryDate(txtExpDate.getText());
        selectedMedicine.setPrice(txtPrice.getText());

        selectedMedicine.setMedAvail(radioAvail.isSelected());

        // Update the existing Medicine in the MedicineCatalog
        PharmacyDirectory pharmacyDirectory = business.getPharmacyDirectory();
        MedicineCatalog medicineCatalog = pharmacyDirectory.getMedicineCatalog();
        medicineCatalog.updateMedicine(selectedMedicine);
      }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtExpDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpDate1ActionPerformed

    private void txtExpDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExpDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExpDateActionPerformed

    private void radioAvailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAvailActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_radioAvailActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblExpDate;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JLabel lblStockAvail;
    private javax.swing.JLabel lblStockAvail1;
    private javax.swing.JLabel lblStockAvail2;
    private javax.swing.JRadioButton radioAvail;
    private javax.swing.JRadioButton radioUnavail;
    private java.awt.TextField txtExpDate;
    private java.awt.TextField txtExpDate1;
    private java.awt.TextField txtMedName;
    private java.awt.TextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
