/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.doctor;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.DoctorProfile;
import com.enterprise.main.ui.patient.BookingAppointment;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JPanel;

/**
 *
 * @author karthikv
 */
public class AppointmentDetails extends javax.swing.JPanel {

    /**
     * Creates new form AppointmentDetails
     */
    
    
    JPanel CardSequencePanel;
    Business business;
    DoctorProfile doctorsProfile;
    Properties properties;
     public AppointmentDetails(JPanel CardSequencePanel, Business business, DoctorProfile doctorsProfile, Properties properties) {
        initComponents();
          this.properties=properties;
        this.CardSequencePanel=CardSequencePanel;
        this.business=business;
        this.doctorsProfile=doctorsProfile;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jpanelMenu = new javax.swing.JPanel();
        btnActiveAppointment = new javax.swing.JButton();
        btnPreviousAppointment = new javax.swing.JButton();
        jpanelWorkArea = new javax.swing.JPanel();

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnActiveAppointment.setText("Active Appointment");
        btnActiveAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveAppointmentActionPerformed(evt);
            }
        });

        btnPreviousAppointment.setText("Previous Appointments");
        btnPreviousAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousAppointmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelMenuLayout = new javax.swing.GroupLayout(jpanelMenu);
        jpanelMenu.setLayout(jpanelMenuLayout);
        jpanelMenuLayout.setHorizontalGroup(
            jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnPreviousAppointment)
                .addGap(29, 29, 29)
                .addComponent(btnActiveAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jpanelMenuLayout.setVerticalGroup(
            jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelMenuLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jpanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreviousAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActiveAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jSplitPane1.setTopComponent(jpanelMenu);

        jpanelWorkArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jpanelWorkArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActiveAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveAppointmentActionPerformed
           PreviousConsultationDetails previousConsultationDetails=new PreviousConsultationDetails(jpanelWorkArea,business,doctorsProfile,properties);
        jpanelWorkArea.add("PreviousConsultationDetails", previousConsultationDetails);
        CardLayout layout=(CardLayout) jpanelWorkArea.getLayout();
        layout.next(jpanelWorkArea); 
    }//GEN-LAST:event_btnActiveAppointmentActionPerformed

    private void btnPreviousAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousAppointmentActionPerformed
          CompletedAppointmentUI completedConsultationDetails=new CompletedAppointmentUI(jpanelWorkArea,business,doctorsProfile,properties);
        jpanelWorkArea.add("CompletedAppointmentUI", completedConsultationDetails);
        CardLayout layout=(CardLayout) jpanelWorkArea.getLayout();
        layout.next(jpanelWorkArea);
    }//GEN-LAST:event_btnPreviousAppointmentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActiveAppointment;
    private javax.swing.JButton btnPreviousAppointment;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel jpanelMenu;
    private javax.swing.JPanel jpanelWorkArea;
    // End of variables declaration//GEN-END:variables
}
