/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.doctor;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.DoctorProfile;
import com.enterprise.main.Profiles.PatientProfile;
import java.awt.Button;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.ButtonGroup;
import javax.swing.JPanel;
import com.enterprise.main.appointment.Appointment;
import com.enterprise.main.appointment.report.PatientReport;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author karthikv
 */
public class PatientReportForm extends javax.swing.JPanel {

    /**
     * Creates new form PatientReportForm
     */
    Appointment appointment;
        PatientProfile patient;
     JPanel jpanelWorkArea;
    Business business;
    DoctorProfile doctorsProfile;
    Properties properties;
    public PatientReportForm(JPanel jpanelWorkArea, Business business, DoctorProfile doctorsProfile, Properties properties,PatientProfile patient,Appointment appointment) {
        initComponents();
        this.appointment=appointment;
          this.properties=properties;
        this.jpanelWorkArea=jpanelWorkArea;
        this.business=business;
        this.doctorsProfile=doctorsProfile;
        this.patient=patient;
        populate();
        ButtonGroup bg=new ButtonGroup();
        bg.add(btnAlcoholYes);
        bg.add(btnNoAlcohol);
        
            ButtonGroup bg1=new ButtonGroup();
        bg1.add(btnHealth);
        bg1.add(btnhealthNo);
        
            ButtonGroup bg2=new ButtonGroup();
        bg2.add(btnhealthNo);
        bg2.add(btnhealthNo);
        
            ButtonGroup bg3=new ButtonGroup();
        bg3.add(allergiesYes);
        bg3.add(allergiesNo);
        
        
            ButtonGroup bg4=new ButtonGroup();
        bg4.add(medsbtnYes);
        bg4.add(medsNo);
        
           ButtonGroup bg5=new ButtonGroup();
        bg5.add(btnNoAlcohol);
        bg5.add(btnAlcoholYes);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoctorsName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checkSymptop1 = new javax.swing.JCheckBox();
        checkSymptop2 = new javax.swing.JCheckBox();
        checkSymptop3 = new javax.swing.JCheckBox();
        checkSymptop4 = new javax.swing.JCheckBox();
        checkSymptop5 = new javax.swing.JCheckBox();
        txtConsultationId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        allergiesYes = new javax.swing.JRadioButton();
        allergiesNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        medsbtnYes = new javax.swing.JRadioButton();
        medsNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnHealth = new javax.swing.JRadioButton();
        btnhealthNo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHeartBeat = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadditional = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnNoAlcohol = new javax.swing.JRadioButton();
        btnAlcoholYes = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        btnSmokingNo = new javax.swing.JRadioButton();
        btnSmokingYes = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfeedback = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Report");

        jLabel2.setText("Patient Name:");

        jLabel3.setText("Doctors Name");

        jLabel4.setText("Symptoms");

        jLabel5.setText("Consultation Id:");

        checkSymptop1.setText("Fever");

        checkSymptop2.setText("Throat Infection");

        checkSymptop3.setText("Dizzy");

        checkSymptop4.setText("Chest Pain");

        checkSymptop5.setText("Unable Feel Smell");
        checkSymptop5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSymptop5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Allergies");

        allergiesYes.setText("Yes");

        allergiesNo.setText("No");

        jLabel7.setText("On Medication");

        medsbtnYes.setText("Yes");

        medsNo.setText("No");

        jLabel8.setText("Past Surgeries or HealthIssue");

        btnHealth.setText("Yes");

        btnhealthNo.setText("No");
        btnhealthNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhealthNoActionPerformed(evt);
            }
        });

        jLabel9.setText("Heart Beat");

        jLabel10.setText("Blood Pressure");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Additional Infomation");

        txtadditional.setColumns(20);
        txtadditional.setRows(5);
        jScrollPane1.setViewportView(txtadditional);

        jLabel12.setText("Regular Alcohol");

        btnNoAlcohol.setText("No");

        btnAlcoholYes.setText("Yes");

        jLabel13.setText("Regular Smoking ");

        btnSmokingNo.setText("No");

        btnSmokingYes.setText("Yes");

        jLabel14.setText("Feedback and Prescription");

        txtfeedback.setColumns(20);
        txtfeedback.setRows(5);
        jScrollPane2.setViewportView(txtfeedback);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(150, 150, 150)
                .addComponent(txtConsultationId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(64, 64, 64)
                .addComponent(txtDoctorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel6)
                .addGap(196, 196, 196)
                .addComponent(allergiesYes)
                .addGap(18, 18, 18)
                .addComponent(allergiesNo))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(84, 84, 84)
                .addComponent(checkSymptop1)
                .addGap(111, 111, 111)
                .addComponent(jLabel7)
                .addGap(160, 160, 160)
                .addComponent(medsbtnYes)
                .addGap(18, 18, 18)
                .addComponent(medsNo))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(checkSymptop2)
                .addGap(54, 54, 54)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnHealth)
                .addGap(15, 15, 15)
                .addComponent(btnhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(checkSymptop3)
                .addGap(112, 112, 112)
                .addComponent(jLabel12)
                .addGap(155, 155, 155)
                .addComponent(btnAlcoholYes)
                .addGap(18, 18, 18)
                .addComponent(btnNoAlcohol))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(checkSymptop4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(checkSymptop5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(85, 85, 85)
                        .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(58, 58, 58)
                        .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel14)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(143, 143, 143)
                        .addComponent(btnSmokingYes)
                        .addGap(18, 18, 18)
                        .addComponent(btnSmokingNo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addGap(466, 466, 466)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5))
                    .addComponent(txtConsultationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(txtDoctorsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(allergiesYes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(allergiesNo)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSymptop1)
                    .addComponent(medsbtnYes)
                    .addComponent(medsNo)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSymptop2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8))
                    .addComponent(btnHealth)
                    .addComponent(btnhealthNo))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkSymptop3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel12))
                    .addComponent(btnAlcoholYes)
                    .addComponent(btnNoAlcohol))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkSymptop4)
                        .addGap(6, 6, 6)
                        .addComponent(checkSymptop5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel9))
                            .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10))
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13))
                            .addComponent(btnSmokingYes)
                            .addComponent(btnSmokingNo))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton2))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkSymptop5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSymptop5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkSymptop5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String symptoms="";
       String bP= txtBloodPressure.getText();
       String heartBeat=txtHeartBeat.getText();
       String addtionalInfo=txtadditional.getText();
       String feedback=txtfeedback.getText();
      boolean allergies = false;
              boolean ishealthisuue=false;

 boolean isalcohol = false;
                boolean issmoking = false;
       if(btnAlcoholYes.isSelected()) {
            isalcohol=true;
       }
       if(btnNoAlcohol.isSelected()){
                    isalcohol=false;
   
       }
       if(btnHealth.isSelected()) {
            ishealthisuue=true;
       }
        
        if(btnhealthNo.isSelected()){
                        ishealthisuue=false;

        }
        if(btnSmokingYes.isSelected()){
                        issmoking=true;

        }
        
        if(btnSmokingNo.isSelected()) {
                        issmoking=false;

        }
        if(allergiesNo.isSelected()) {
                        allergies=true;

        }
        
        if(allergiesYes.isSelected()) {
                        allergies=false;

        }
        boolean ismeds = false;
        if(medsNo.isSelected()) {
                        ismeds=true;

        }
        if(medsbtnYes.isSelected()) {
                        ismeds=false;

        }
       if(checkSymptop1.isSelected()) {
           
           symptoms=symptoms+" "+checkSymptop1.getText();
       }
        if(checkSymptop2.isSelected()) {
           
           symptoms=symptoms+" "+checkSymptop2.getText();
       } if(checkSymptop3.isSelected()) {
           
           symptoms=symptoms+" "+checkSymptop3.getText();
       } if(checkSymptop4.isSelected()) {
           
           symptoms=symptoms+" "+checkSymptop4.getText();
       } if(checkSymptop5.isSelected()) {
           
           symptoms=symptoms+" "+checkSymptop5.getText();
       }
        PatientReport patientReport=new PatientReport();
        patientReport.setAddtional(addtionalInfo);
        patientReport.setAllergies(allergies);
        patientReport.setFeedback(feedback);
        patientReport.setPastSurgeriesorhealthIssue(ishealthisuue);
        
        patientReport.setPatientprofile(patient);
        patientReport.setDoctorProfile(doctorsProfile);
                patientReport.setAppointment(appointment);
        patientReport.setIsSmoking(issmoking);

        patientReport.setIsalcohol(isalcohol);
        patientReport.setOnmedication(ismeds);
        patientReport.setSymptoms(symptoms);
        appointment.setReport(patientReport);
        appointment.setAppointmentStatus("Completed without Feedback");
        
        
        int appointmentIdToUpdate = appointment.getAppointmentid();
        String newStatus = "Completed without Feedback";
        String url = properties.getProperty("url");
        String userdbName = properties.getProperty("userdbName");
        String pass = properties.getProperty("passwordDB");
        
         try ( Connection connection = DriverManager.getConnection(url, userdbName, pass)) {
                String updateQuery = "UPDATE mydoctor.Appointments SET appointmentStatus = ? WHERE appointmentid = ?";
                try ( PreparedStatement preparedStatement = connection.prepareStatement(updateQuery)) {
                    preparedStatement.setString(1, newStatus);
                    preparedStatement.setInt(2, appointmentIdToUpdate);
                    int rowsAffected = preparedStatement.executeUpdate();
                    System.out.println(rowsAffected + " row(s) updated.");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }
          try (Connection connection = DriverManager.getConnection(url, userdbName, pass)) {
            String insertSql = "INSERT INTO mydoctor.patientreports " +
                    "(patientid, doctorid, symptoms, allergies, onmedication, " +
                    "pastSurgeriesorhealthIssue, isSmoking, isalcohol, " +
                    "bloodPressure, heartBeat, additional, feedback, appointment) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            try (PreparedStatement preparedStatement = connection.prepareStatement(insertSql)) {
                preparedStatement.setInt(1, patient.getPerson().getId());
                preparedStatement.setInt(2, doctorsProfile.getPerson().getId());
                preparedStatement.setString(3, symptoms);
                preparedStatement.setBoolean(4, allergies);
                preparedStatement.setBoolean(5, ismeds);
                preparedStatement.setBoolean(6, ishealthisuue);
                preparedStatement.setBoolean(7, issmoking);
                preparedStatement.setBoolean(8, isalcohol);
                preparedStatement.setString(9, bP);
                preparedStatement.setString(10, heartBeat);
                preparedStatement.setString(11, addtionalInfo);
                preparedStatement.setString(12, feedback);
                preparedStatement.setInt(13, appointment.getAppointmentid());

                int rowsAffected = preparedStatement.executeUpdate();

                System.out.println("Rows affected: " + rowsAffected);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
        
        
        JOptionPane.showMessageDialog(this, "Report Submitted Sucessfully");
        

        jpanelWorkArea.remove(1);
        ((java.awt.CardLayout) jpanelWorkArea.getLayout()).next(jpanelWorkArea);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnhealthNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhealthNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhealthNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                jpanelWorkArea.remove(this);
        ((java.awt.CardLayout) jpanelWorkArea.getLayout()).next(jpanelWorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergiesNo;
    private javax.swing.JRadioButton allergiesYes;
    private javax.swing.JRadioButton btnAlcoholYes;
    private javax.swing.JRadioButton btnHealth;
    private javax.swing.JRadioButton btnNoAlcohol;
    private javax.swing.JRadioButton btnSmokingNo;
    private javax.swing.JRadioButton btnSmokingYes;
    private javax.swing.JRadioButton btnhealthNo;
    private javax.swing.JCheckBox checkSymptop1;
    private javax.swing.JCheckBox checkSymptop2;
    private javax.swing.JCheckBox checkSymptop3;
    private javax.swing.JCheckBox checkSymptop4;
    private javax.swing.JCheckBox checkSymptop5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton medsNo;
    private javax.swing.JRadioButton medsbtnYes;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtConsultationId;
    private javax.swing.JTextField txtDoctorsName;
    private javax.swing.JTextField txtHeartBeat;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtadditional;
    private javax.swing.JTextArea txtfeedback;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        txtName.setText(patient.getPerson().getFirstName()+"  "+patient.getPerson().getLastName());
                txtDoctorsName.setText(doctorsProfile.getPerson().getFirstName()+"  "+doctorsProfile.getPerson().getLastName());
txtConsultationId.setText(String.valueOf(appointment.getAppointmentid()));


    }
}
