/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.admin;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.PatientProfile;
import com.enterprise.main.appointment.Appointment;
import com.enterprise.main.appointment.AppointmentDirectory;
import com.enterprise.main.directory.PatientDirectory;
import com.enterprise.main.ui.doctor.PatientDetailsSection;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karthikv
 */
public class PatientAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientAdminPanel
     */
    JPanel CardSequencePanel;
    Business business;
    Properties properties;
    public PatientAdminPanel(JPanel CardSequencePanel, Business business, Properties properties) {
        initComponents();
        this.CardSequencePanel=CardSequencePanel;
        this.business=business;
        this.properties=properties;
        
        populate();
        
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "UserId", "Email Id", "Gender"
            }
        ));
        jScrollPane1.setViewportView(tblPatients);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit Profile");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Refresh");

        jButton5.setText("Search");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(91, 91, 91)
                            .addComponent(jButton3)
                            .addGap(99, 99, 99)
                            .addComponent(jButton4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        int row = tblPatients.getSelectedRow();
        if(row<0) {
                JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
    
            return;
        }
        
        int id = (int) tblPatients.getValueAt(row, 0);
        PatientProfile profile=business.getPatientdirectory().findPatient(id);
        

        PatientProfile patient=business.getPatientdirectory().findPatient(id);
        business.getPatientdirectory().deleteAppointment(patient);
        
        JOptionPane.showMessageDialog(this,"The User Profile has been Deleted");
        populate();
//        business.get
        
        
//        PatientDetailsSection patientDetailsSection=new PatientDetailsSection(jpanelWorkArea,business,doctorsProfile,properties,patient);
//        jpanelWorkArea.add("PatientDetailsSection", patientDetailsSection);
//        CardLayout layout=(CardLayout) jpanelWorkArea.getLayout();
//        layout.next(jpanelWorkArea);   
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           String searchKeyword = jTextField1.getText().trim().toLowerCase();

    if (searchKeyword.isEmpty()) {
        populate();
    } else {
        performSearch(searchKeyword);
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void performSearch(String searchKeyword) {
    DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
    PatientDirectory patientDirectory = business.getPatientdirectory();
    model.setRowCount(0);

    for (PatientProfile patientProfile : patientDirectory.getPatientList()) {
        String username = patientProfile.getPerson().getUserName().toLowerCase();
        String name = (patientProfile.getPerson().getFirstName() + " " + patientProfile.getPerson().getLastName()).toLowerCase();
        String userId = patientProfile.getPerson().getUserName().toLowerCase();

        if (String.valueOf(patientProfile.getPerson().getId()).equals(searchKeyword) ||
            username.contains(searchKeyword) ||
            name.contains(searchKeyword) ||
            userId.equals(searchKeyword)) {
            Object row[] = new Object[5];
            row[0] = patientProfile.getPerson().getId();
            row[1] = patientProfile.getPerson().getFirstName() + " " + patientProfile.getPerson().getLastName();
            row[2] = patientProfile.getPerson().getUserName();
            row[3] = patientProfile.getPerson().getEmailId();
            row[4] = patientProfile.getGender();
            ((DefaultTableModel) tblPatients.getModel()).addRow(row);
        }
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblPatients;
    // End of variables declaration//GEN-END:variables

    private void populate() {
        
        DefaultTableModel model = (DefaultTableModel) tblPatients.getModel();
        PatientDirectory patientDirectory = business.getPatientdirectory();
        model.setRowCount(0);
        for (PatientProfile patientProfile : patientDirectory.getPatientList()) {
                 Object row[] = new Object[5];
            row[0]=patientProfile.getPerson().getId();
            row[1] = patientProfile.getPerson().getFirstName()+ " " +patientProfile.getPerson().getLastName();
            row[2] = patientProfile.getPerson().getUserName();
            row[3] = patientProfile.getPerson().getEmailId();
            row[4] = patientProfile.getGender();
            ((DefaultTableModel) tblPatients.getModel()).addRow(row);
            
            
        }
    }
    
    
}
