/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.patient;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.DoctorProfile;
import com.enterprise.main.Profiles.PatientProfile;
import com.enterprise.main.appointment.report.PatientReport;
import java.util.Properties;
import javax.swing.JPanel;

/**
 *
 * @author karthikv
 */
public class DisplayReport extends javax.swing.JPanel {
   JPanel jpanelWorkArea;
    Business business;
    Properties properties;
    PatientProfile patient;
    PatientReport patientReport;
    int appointmentId;
    /**
     * Creates new form DisplayReport
     */
    public DisplayReport(JPanel jpanelWorkArea, Business business, Properties properties, PatientProfile patient, PatientReport patientReport, int appointmentId) {
        initComponents();
        this.appointmentId=appointmentId;
         this.patientReport=patientReport;
            this.properties=properties;
        this.jpanelWorkArea=jpanelWorkArea;
        this.business=business;
        this.patient=patient;
        populate();
    }

private void populate() {
        
        txtBloodPressure.setText(patientReport.getBloodPressure());
        txtDoctorsName.setText(business.getAppointmentDirectory().findAppointmentbyId(appointmentId).getDoctorProfile().getPerson().getFirstName()+" "+business.getAppointmentDirectory().findAppointmentbyId(appointmentId).getDoctorProfile().getPerson().getFirstName());
        txtName.setText(patient.getPerson().getFirstName()+" "+patient.getPerson().getLastName());
        txtHeartBeat.setText(patientReport.getBloodPressure());
        txtadditional1.setText(patientReport.getSymptoms());
        txtadditional.setText(patientReport.getAddtional());
        txtfeedback.setText(patientReport.getFeedback());
        if(patientReport.isAllergies()) {
            allergiesYes.setSelected(true);
            allergiesNo.setEnabled(false);
        }
        else{
            allergiesNo.setSelected(true);
                        allergiesYes.setEnabled(false);

        }
        
         if(patientReport.isIsSmoking()) {
            btnSmokingYes.setSelected(true);
            btnSmokingNo.setEnabled(false);
        }
        else{
            btnSmokingNo.setSelected(true);
                        btnSmokingYes.setEnabled(false);

        }
         
          if(patientReport.isIsalcohol()) {
            btnAlcoholYes.setSelected(true);
            btnNoAlcohol.setEnabled(false);
        }
        else{
            btnNoAlcohol.setSelected(true);
                        btnAlcoholYes.setEnabled(false);

        }
          
          
           if(patientReport.isOnmedication()) {
            medsbtnYes.setSelected(true);
            medsNo.setEnabled(false);
        }
        else{
            medsNo.setSelected(true);
                        medsbtnYes.setEnabled(false);

        }
                  if(patientReport.isPastSurgeriesorhealthIssue()) {
            btnHealth.setSelected(true);
            btnhealthNo.setEnabled(false);
        }
        else{
            btnhealthNo.setSelected(true);
                        btnHealth.setEnabled(false);

        }


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDoctorsName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        allergiesYes = new javax.swing.JRadioButton();
        allergiesNo = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        medsbtnYes = new javax.swing.JRadioButton();
        medsNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        btnHealth = new javax.swing.JRadioButton();
        btnhealthNo = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtHeartBeat = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtadditional = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btnNoAlcohol = new javax.swing.JRadioButton();
        btnAlcoholYes = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        btnSmokingNo = new javax.swing.JRadioButton();
        btnSmokingYes = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtfeedback = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtadditional1 = new javax.swing.JTextArea();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Report");

        jLabel2.setText("Patient Name:");

        txtName.setEditable(false);

        jLabel3.setText("Doctors Name");

        txtDoctorsName.setEditable(false);

        jLabel4.setText("Symptoms");

        jLabel6.setText("Allergies");

        allergiesYes.setText("Yes");

        allergiesNo.setText("No");

        jLabel7.setText("On Medication");

        medsbtnYes.setText("Yes");

        medsNo.setText("No");

        jLabel8.setText("Past Surgeries or HealthIssue");

        btnHealth.setText("Yes");

        btnhealthNo.setText("No");
        btnhealthNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhealthNoActionPerformed(evt);
            }
        });

        jLabel9.setText("Heart Beat");

        jLabel10.setText("Blood Pressure");

        txtHeartBeat.setEditable(false);

        txtBloodPressure.setEditable(false);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Additional Infomation");

        txtadditional.setEditable(false);
        txtadditional.setColumns(20);
        txtadditional.setRows(5);
        jScrollPane1.setViewportView(txtadditional);

        jLabel12.setText("Regular Alcohol");

        btnNoAlcohol.setText("No");

        btnAlcoholYes.setText("Yes");

        jLabel13.setText("Regular Smoking ");

        btnSmokingNo.setText("No");

        btnSmokingYes.setText("Yes");

        jLabel14.setText("Feedback and Prescription");

        txtfeedback.setEditable(false);
        txtfeedback.setColumns(20);
        txtfeedback.setRows(5);
        jScrollPane2.setViewportView(txtfeedback);

        txtadditional1.setEditable(false);
        txtadditional1.setColumns(20);
        txtadditional1.setRows(5);
        jScrollPane3.setViewportView(txtadditional1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDoctorsName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(btnHealth)
                                                .addGap(15, 15, 15)
                                                .addComponent(btnhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addGap(155, 155, 155)
                                                .addComponent(btnAlcoholYes)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnNoAlcohol)))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(143, 143, 143)
                                            .addComponent(btnSmokingYes)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnSmokingNo))
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addGap(553, 553, 553)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(allergiesYes)
                                .addGap(18, 18, 18)
                                .addComponent(allergiesNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medsbtnYes)
                                .addGap(18, 18, 18)
                                .addComponent(medsNo)))))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtDoctorsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(allergiesYes)
                            .addComponent(allergiesNo)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(medsbtnYes)
                                .addComponent(medsNo)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel8))
                            .addComponent(btnHealth)
                            .addComponent(btnhealthNo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel12))
                            .addComponent(btnAlcoholYes)
                            .addComponent(btnNoAlcohol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13))
                            .addComponent(btnSmokingYes)
                            .addComponent(btnSmokingNo))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHeartBeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel14))
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnhealthNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhealthNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhealthNoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jpanelWorkArea.remove(this);
        ((java.awt.CardLayout) jpanelWorkArea.getLayout()).next(jpanelWorkArea);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allergiesNo;
    private javax.swing.JRadioButton allergiesYes;
    private javax.swing.JRadioButton btnAlcoholYes;
    private javax.swing.JRadioButton btnHealth;
    private javax.swing.JRadioButton btnNoAlcohol;
    private javax.swing.JRadioButton btnSmokingNo;
    private javax.swing.JRadioButton btnSmokingYes;
    private javax.swing.JRadioButton btnhealthNo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton medsNo;
    private javax.swing.JRadioButton medsbtnYes;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtDoctorsName;
    private javax.swing.JTextField txtHeartBeat;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextArea txtadditional;
    private javax.swing.JTextArea txtadditional1;
    private javax.swing.JTextArea txtfeedback;
    // End of variables declaration//GEN-END:variables
}
