/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.patient;

import com.enterprise.main.Business;
import com.enterprise.main.HomePage;
import com.enterprise.main.HomePageLanding;
import com.enterprise.main.Profiles.PatientProfile;
import com.enterprise.main.ui.doctor.PatientDetailsSection;
import com.enterprise.main.ui.patient.BookingAppointment;
import java.awt.CardLayout;
import java.util.Properties;
import javax.swing.JPanel;

/**
 *
 * @author karthikv
 */
public class LandingPagePatient extends javax.swing.JPanel {
    javax.swing.JPanel CardSequencePanel;
 Business business;
 PatientProfile patientProfile;
    Properties properties;
    /**
     * Creates new form LandingPagePatient
     */
    public LandingPagePatient(JPanel CardSequencePane, Business business, PatientProfile patientProfile, Properties properties) {
        initComponents();
        this.properties=properties;
        this.CardSequencePanel=CardSequencePane;
        this.business=business;
        this.patientProfile=patientProfile;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        menuBar = new javax.swing.JPanel();
        btnBookAppointment = new javax.swing.JButton();
        btnOrderMedicines = new javax.swing.JButton();
        btnLabs = new javax.swing.JButton();
        brnHealthRecords = new javax.swing.JButton();
        btnProfiles = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        btnBookAppointment.setText("Book an Appointment");
        btnBookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAppointmentActionPerformed(evt);
            }
        });

        btnOrderMedicines.setText("Medicines");
        btnOrderMedicines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMedicinesActionPerformed(evt);
            }
        });

        btnLabs.setText("Lab Tests");
        btnLabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabsActionPerformed(evt);
            }
        });

        brnHealthRecords.setText("Health Records");
        brnHealthRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnHealthRecordsActionPerformed(evt);
            }
        });

        btnProfiles.setText("Profile");
        btnProfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfilesActionPerformed(evt);
            }
        });

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBookAppointment)
                .addGap(18, 18, 18)
                .addComponent(btnOrderMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLabs)
                .addGap(18, 18, 18)
                .addComponent(brnHealthRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBookAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrderMedicines, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabs, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnHealthRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProfiles, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(menuBar);

        workArea.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(workArea);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAppointmentActionPerformed
        // TODO add your handling code here:
          BookingAppointment bookingAppointment=new BookingAppointment(workArea,business,patientProfile,properties);
        workArea.add("ManagerAppointmentBookingDetails", bookingAppointment);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnBookAppointmentActionPerformed

    private void btnProfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilesActionPerformed
        // TODO add your handling code here:
        ProfileDetails profile=new ProfileDetails(CardSequencePanel,business,properties,patientProfile);
        CardSequencePanel.add("ProfileDetails", profile);
        CardLayout layout=(CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
        
    }//GEN-LAST:event_btnProfilesActionPerformed

    private void btnOrderMedicinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMedicinesActionPerformed
        // TODO add your handling code here:
                  OrderMedsJPanel orderMedsJPanel=new OrderMedsJPanel(workArea,business,patientProfile,properties);
        workArea.add("OrderMedsJPanel", orderMedsJPanel);
        CardLayout layout=(CardLayout) workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnOrderMedicinesActionPerformed

    private void btnLabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabsActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
            TabelLabs listofPatientReports=new TabelLabs(CardSequencePanel,business,properties,patientProfile);
        CardSequencePanel.add("ListPanelForm", listofPatientReports);
        CardLayout layout=(CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
      
    }//GEN-LAST:event_btnLabsActionPerformed

    private void brnHealthRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnHealthRecordsActionPerformed
        // TODO add your handling code here:
        DetailsPatient detailsSection=new DetailsPatient(CardSequencePanel,business,properties,patientProfile);
        CardSequencePanel.add("PatientDetailsSection", detailsSection);
        CardLayout layout=(CardLayout) CardSequencePanel.getLayout();
        layout.next(CardSequencePanel);
    }//GEN-LAST:event_brnHealthRecordsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        CardSequencePanel.removeAll();
  
        HomePageLanding homeprof = new HomePageLanding(business);
        CardSequencePanel.add("HomePageLanding", homeprof);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnHealthRecords;
    private javax.swing.JButton btnBookAppointment;
    private javax.swing.JButton btnLabs;
    private javax.swing.JButton btnOrderMedicines;
    private javax.swing.JButton btnProfiles;
    private javax.swing.JButton jButton1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel menuBar;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables

}
