/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.enterprise.main.ui.patient;

import com.enterprise.main.Business;
import com.enterprise.main.Profiles.PatientProfile;
import com.enterprise.main.appointment.Appointment;
import com.enterprise.main.appointment.AppointmentDirectory;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karthikv
 */


public class PendingReviewAppointments extends javax.swing.JPanel {
  javax.swing.JPanel CardSequencePanel;
 Business business;
 PatientProfile patientProfile;
    Properties properties;
    /**
     * Creates new form PendingReviewAppointments
     */
    public PendingReviewAppointments(JPanel CardSequencePanel, Business business, PatientProfile patientProfile, Properties properties) {
        initComponents();
          this.properties=properties;
        this.CardSequencePanel=CardSequencePanel;
        this.business=business;
        this.patientProfile=patientProfile;
        populate();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReports = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        tblReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Patient Name", "Doctors Name", "Appointmenrt Number", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblReports);

        jButton1.setText("Submitted Feedback");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Feedback");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(103, 103, 103)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(225, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 String id=jTextField1.getText();
//        String rating =txtProfessorName.getText();

        int row = tblReports.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(this, "Please select a row.", "Error", JOptionPane.ERROR_MESSAGE);

            return;
        }
         int value=Integer.parseInt((jTextField1.getText()));        
         
         int appointmentId = (int) tblReports.getValueAt(row, 2);
        System.out.println(appointmentId);
        Appointment appointment=business.getAppointmentDirectory().findAppointmentbyId(appointmentId);
        appointment.getDoctorProfile().addRating(value);
        
        
        JOptionPane.showMessageDialog(this, "Review Submitted");
        
    }//GEN-LAST:event_jButton1ActionPerformed

private void populate() {
           DefaultTableModel model = (DefaultTableModel) tblReports.getModel();
        AppointmentDirectory appointmentDirectory = business.getAppointmentDirectory();
        model.setRowCount(0);

        for (Appointment appointment : appointmentDirectory.getAppointmentList()) {
            if(appointment.getPatientProfile().getPerson().getId()==patientProfile.getPerson().getId()) {
                if(appointment.getAppointmentStatus().equals("Completed without Feedback")) {
                 Object row[] = new Object[6];
            PatientProfile patientprofile=appointmentDirectory.findPatientbyAppointment(appointment.getAppointmentid());
            row[0] = patientprofile.getPerson().getFirstName()+ " " +patientprofile.getPerson().getLastName();
            row[1] = appointment.getDoctorProfile().getPerson().getFirstName()+ " " +appointment.getDoctorProfile().getPerson().getLastName();
            row[2] = appointment.getAppointmentid();
            row[3] = appointment.getAppointmentStatus();
            ((DefaultTableModel) tblReports.getModel()).addRow(row);
            }
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblReports;
    // End of variables declaration//GEN-END:variables
}
